---
- name: Install PECL libaries.
  command: "pecl install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "('already installed' not in pecl_result.stdout) or ('install ok:' not in pecl_result.stdout)"
  with_items: php_pecl_extensions
